version: '3.1'
services:
  app:
    build: .
    image: powerfulyang/api.powerfulyang.com
    container_name: api.powerfulyang.com
    ports:
      - '3000:3000'
    environment:
      'NODE_ENV': 'production'
      'SecretId': ${SecretId}
      'SecretKey': ${SecretKey}
    restart: always
    networks:
      - dev-net
    volumes:
      - ./upload:/usr/app/upload
    command: npm run start:prod
    env_file:
      - .env


networks:
  dev-net:
    external: true
