name: app

on:
  push:
    paths:
    - package.json
    - Dockerfile.base
    - .github/workflows/base.yml

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-repository: [powerfulyang/api.powerfulyang.com.base]
    steps:
      - uses: actions/checkout@v2
      - name: Dockerize
        id: dockerize
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ matrix.docker-repository }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest"
          dockerfile: Dockerfile.base
